### ISSUE TITLE
Clone succeeded, but checkout failed. 

### ISSUE THREAD

**Issue by magnusnn** [dvikan/old-ntnu-exams#17]
Mulig å gjøre cleanup av mappe-/filnavn? Ved cloning av repo til windows skjer det noe med navnsettingen på alle mapper og den spyr ut følgende i consolen 
```
...
Checking connectivity... done.
error: unable to create file TDT4140_Systemutvikling/Doc/index.html?C=D;O=A (Invalid argument)
error: unable to create file TDT4140_Systemutvikling/Doc/index.html?C=M;O=A (Invalid argument)
error: unable to create file TDT4140_Systemutvikling/Doc/index.html?C=M;O=D (Invalid argument)
error: unable to create file TDT4140_Systemutvikling/Doc/index.html?C=S;O=A (Invalid argument)
error: unable to create file TDT4140_Systemutvikling/Doc/index.html?C=S;O=D (Invalid argument)
fatal: cannot create directory at 'TMM4225-Ingeniørrettet-samhandling-i-distribuerte-team:-Ledelse-og-smart-bruk': Invalid argument
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

Ved `git status` er alle mappene slettet og opprettet på ny sånn at man må adde de inn og committe. Får du gjort noe med dette?

**Comment by dvikan** [comment]
Takk. Skal se på det. Er du inni cygwin på windows? Eller git bash?

**Comment by magnusnn** [comment]
Git bash tipper jeg, bare jeg kjører det i cmd, skal vel ikke ha noe å si at det er cmd istedenfor rett i bash?

**Comment by odinuge** [comment]
Dette er på grunn av at windows ikke tillater alle tegn i fil/mappenavn. [Her](https://msdn.microsoft.com/en-us/library/aa365247) er link til MS sine "Naming Conventions". Alle de filene/mappene som feiler ved checkout inneholder noen av de reserverte tegnene, som ikke tillates i windows. I dette tilfellet `?` og `:`.

Kan sikkert sende en PR hvis ingen andre kommer meg i forkjøpet.
